### ISSUE TITLE
[QUE] How is it possible?

### ISSUE THREAD

**Issue by gosandra** [krisior/aurora-reader#4]
**Ask a question**
How is it possible?

**Express your demands**
![image](https://user-images.githubusercontent.com/72603100/135318224-8b9fc500-a413-41df-af59-52019143e5eb.png)

**Specific OS version and/or device type**
 - OS: W10
 - Device: Laptop Dell Inspiron

**Additional context**

<3

**Comment by krzysiecc** [comment]
We don't know, but it looks good. Good job!

**Thank you** for any actions taken to make our project better. We will discuss it at the nearest opportunity.

In the meantime, you can go on our website and check for new updates and stuff waiting for you. 
Best regards, Aurora Team
